#!/usr/bin/env bash
# d-and-e.sh
# Download and Extract (not the thing the GOP want to eliminate)
#
# (Mostly) Generated by Microsoft Copilot with a bit of coaxing
# (and quite a bit of annoyance)

# Detect if this file is being sourced or run directly
# BASH_SOURCE[0] is the current file, $0 is the script name
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # This file is being executed directly
    echo "⚠️ This script should be sourced, not executed."
    exit 1
fi

# Initialize variables ...?
needed_files=()
filenames=()
sigfiles=()
all_present=true
FILES=()
SIGS=()

# --- Wrapper functions for consistent defaults ---
curl_wrapper() {
    curl --config "${SOURCE_ROOT}/.curlrc" "$@"
}

gpgv_wrapper() {
    gpgv --weak-digest reject "$@"
}

gpg_wrapper() {
    with_keyring_lock gpg "$@"
}

cleanup() {
    rm -f /tmp/lotto_org.* /tmp/lotto_ur.* "${LOCKFILE:-}"
}
{
    trap 'echo "Interrupted (INT), cleaning up…" >&2; cleanup; exit 130' INT
    trap 'echo "Terminated (TERM), cleaning up…" >&2; cleanup; exit 143' TERM
    trap cleanup EXIT
}

# shellcheck source=../common/lotto.sh
. "${SCRIPT_DIR}/common/lotto.sh"

mkdir -p "${SOURCE_ROOT}" && cd "${SOURCE_ROOT}" || exit 1

# --- Project-local curl defaults ---
CURLRC="${SOURCE_ROOT}/.curlrc"
if [[ ! -f "$CURLRC" ]]; then
    cat >"$CURLRC" <<'EOF'
retry = 5
retry-delay = 2
retry-all-errors
max-time = 30
fail
silent
show-error
EOF
fi

export GNU_BASE_URL="https://ftpmirror.gnu.org/"
# --- Files to fetch (relative to mirror root) ---
GNU_FILES=(
    "binutils/binutils-2.45.tar.bz2"
    "gcc/gcc-15.2.0/gcc-15.2.0.tar.gz"
    #    "mpfr/mpfr-4.2.2.tar.bz2"
    #    "gmp/gmp-6.3.0.tar.bz2"
    #    "mpc/mpc-1.3.1.tar.gz"
    "glibc/glibc-2.42.tar.bz2"
)
for g in "${GNU_FILES[@]}"; do
    FILES+=("$GNU_BASE_URL/$g")
    SIGS+=("$GNU_BASE_URL/$g.sig")
done
MUSL_URL="https://musl.libc.org/releases/musl-1.2.5.tar.gz"
MUSL_SIG="${MUSL_URL}.asc"

FILES+=("$MUSL_URL")
SIGS+=("$MUSL_SIG")
# Hopefully the files and signatures have matching indicies

# --- Check if all files and signatures exist locally ---
for ((i = 0; i < ${#FILES[@]}; i++)); do
    filenames+=("$(basename "${FILES[i]}")")
    sigfiles+=("$(basename "${SIGS[i]}")")
    if [[ ! -f "${filenames[i]}" ]]; then
        all_present=false
        needed_files+=("${FILES[i]}")
    fi
    if [[ ! -f "${sigfiles[i]}" ]]; then
        all_present=false
        needed_files+=("${SIGS[i]}")
    fi
done

# --- Conditional network connectivity test ---
if [[ "$all_present" == false ]]; then
    echo "🌐 Checking network connectivity..."
    if ! curl_wrapper -s --head --max-time 5 http://www.msftconnecttest.com/connecttest.txt >/dev/null; then
        echo "❌ Network check failed using curl. Unable to reach connection test site."
        echo "☎️ Please check your internet connection and try again."
        # If you'd like to make a call, hang up and try again. If you need help, dial the operator
        exit 1
    fi

    echo "📞 Passed. Downloading $((${#needed_files[@]})) files..."
    # Decide parallelism: (2d3)
    rand_byte=$(od -An -N1 -tu1 </dev/urandom)
    jobs=$(((rand_byte % 3 + 1) + ($(od -An -N1 -tu1 </dev/urandom) % 3 + 1)))
    curl --parallel \
        --parallel-max "${jobs}" \
        --remote-name-all \
        "${needed_files[@]}" \
        --location \
        --write-out '%{url_effective} %{http_code}\n' \
        --fail # EMOTIONAL DAMAGE™
else
    echo "📂 All files and signatures found locally — skipping network check."
fi
wait
# --- Persistent workspace keyring ---
LOCAL_GNUPGHOME="${SOURCE_ROOT}/.gnupg-local"
mkdir -p "$LOCAL_GNUPGHOME"
chmod 700 "$LOCAL_GNUPGHOME"
export GNUPGHOME="$LOCAL_GNUPGHOME"

KEYSERVERS=("hkps://keys.openpgp.org" "hkps://keyserver.ubuntu.com")

bad_sigs=()
no_pubkey=()

LOCKFILE="${SOURCE_ROOT}/.gpg-import.lock"

with_keyring_lock() {
    {
        flock 200
        "$@"
    } 200>"$LOCKFILE"
}

verify_sig() {
    set_window_title "Verifying signature for $1"
    local f="$1"
    local sig="$2"

    # Try verification with default keyring as well as local keyring
    if (GNUPGHOME='' gpgv_wrapper --weak-digest reject "$sig" "$f" >/dev/null 2>&1) || gpgv_wrapper "$sig" "$f" >/dev/null 2>&1; then
        return
    fi

    # If both fail, check why
    output=$(gpgv_wrapper --weak-digest reject "$sig" "$f" 2>&1)
    if [[ $output == *"Can't check signature: No public key"* ]]; then
        echo "Can't check signature for $f: No public key"

        # Extract email and keyid from signature
        email=$(gpg --list-packets "$sig" | awk -F'[<>]' '/user ID/ {print $2; exit}')
        keyid=$(gpg --list-packets "$sig" | awk '/keyid/ {print $2; exit}')

        # Try WKD first (local keyring only)
        if [[ -n $email ]]; then
            echo "Trying WKD for $email..."
            rand_delay
            gpg_wrapper --auto-key-locate wkd --locate-key "$email" >/dev/null 2>&1
        fi

        # If WKD failed or no email, try keyservers (local keyring only)
        if ! gpg --list-keys "$keyid" >/dev/null 2>&1; then
            for ks in "${KEYSERVERS[@]}"; do
                echo "Fetching $keyid from $ks..."
                rand_delay
                gpg_wrapper --keyserver "$ks" --recv-keys "$keyid" >/dev/null 2>&1 && break
            done
        fi

        # If key fetched, try WKD again using UID from local keyring
        if gpg --list-keys "$keyid" >/dev/null 2>&1; then
            if [[ -z $email ]]; then
                email=$(GNUPGHOME="$LOCAL_GNUPGHOME" gpg_wrapper --list-keys --with-colons "$keyid" | awk -F: '/uid:/ {print $10; exit}')
            fi
            if [[ -n $email ]]; then
                echo "Verifying $email via WKD..."
                gpg_wrapper --auto-key-locate wkd --locate-key "$email" >/dev/null 2>&1
            fi
        else
            no_pubkey+=("$f")
        fi

    else
        bad_sigs+=("$f")
    fi
}

for ((i = 0; i < ${#filenames[@]}; i++)); do
    verify_sig "${filenames[i]}" "${sigfiles[i]}" &
done
wait

# No entry to Sto-Vo-Kor for those who use printf!!!!!!!! (previous revision used it)
if ((${#bad_sigs[@]} > 0 || ${#no_pubkey[@]} > 0)); then
    echo "ERROR: Bad signatures or unresolved missing keys found — terminating."
    echo "=== Bad Signatures ==="
    if ((${#bad_sigs[@]})); then
        for f in "${bad_sigs[@]}"; do
            echo "$f"
        done
    else
        echo "(none)"
    fi
    echo "=== No Public Key ==="
    if ((${#no_pubkey[@]})); then
        for f in "${no_pubkey[@]}"; do
            echo "$f"
        done
    else
        echo "(none)"
    fi
    exit 1
fi

extract_archive() {
    local tarflags=()
    local filename="$1"
    local mime
    mime=$(file --mime-type -b "$filename")

    base="${filename%.*}" # strip one extension
    base="${base%.*}"     # strip two (e.g. .tar.gz)
    if [ -f "$base/.marker" ]; then
        echo "✅ Extraction marker found, skipping"
        return 0
    fi

    case "$mime" in
    application/x-gzip) tarflags=(-xvzf) ;;
    application/gzip) tarflags=(-xvzf) ;;
    application/x-bzip2) tarflags=(-xvjf) ;;
    application/x-xz) tarflags=(-xvJf) ;;
    application/zstd) tarflags=(--zstd -xvf) ;;
    application/x-tar) tarflags=(-xvf) ;;
    *)
        echo "⚠️ Unknown archive type for $filename ($mime), trying plain tar..."
        tarflags=(-xvf)
        ;;
    esac

    if tar "${tarflags[@]}" "$filename"; then
        touch "$base/.marker"
    fi
}

wait
set_window_title "Extracting ${filenames[*]}"
for f in "${filenames[@]}"; do
    extract_archive "${f}" & # YOLO!
done
wait

cd "${SOURCE_ROOT}"/gcc-*/ || return 1
"${SCRIPT_DIR}"/gcc/dl_gcc_prequisites.sh --directory="${SOURCE_ROOT}"
